remote_theme: chrisbobbe/jekyll-theme-prologue

collections: [sections]

#site settings
title: The Site
subtitle: We built. 
description: >- # this means to ignore newlines until "baseurl:"
  This is the demo site for a Jekyll theme version of
  HTML5 UP's sleek, responsive site template Prologue.
author: Samantha Brake
email: sammy.brake@gmail.com
avatar: https://scontent.fmkc1-1.fna.fbcdn.net/v/t1.0-9/34962229_10156937724617137_8273934344586788864_n.jpg?_nc_cat=0&oh=c7158f8953a9d02b2bc62af201c4aaaf&oe=5BA03ED4

baseurl: 
url: 

# Social settings
facebook_url: https://www.facebook.com/daveycrockettsuperman
github_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/samantha-brake-14717b1a
pinterest_url:
slack_url:
twitter_url:

google_analytics:

